# Generated by Django 2.0.4 on 2018-05-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Templator', '0002_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
        migrations.RemoveField(
            model_name='record',
            name='send_date',
        ),
        migrations.AddField(
            model_name='record',
            name='ok_semesters',
            field=models.CharField(choices=[('ALL', 'Все семестры'), ('1', '1 семестр'), ('2', '2 семестра'), ('3', '3 семестра'), ('4', '4 семестра'), ('5', '5 семестров'), ('6', '6 семестров'), ('7', '7 семестров'), ('8', '8 семестров')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='media', verbose_name='Attachment'),
        ),
    ]
