# Generated by Django 2.0.4 on 2018-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Templator', '0003_auto_20180510_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Attachment'),
        ),
    ]
