# Generated by Django 2.0.4 on 2018-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Templator', '0004_auto_20180517_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='D:\\WebGenerator\\Generator/uploads/media/2018.05.18 12.12.37', verbose_name='Attachment'),
        ),
    ]
