# Generated by Django 2.0.4 on 2018-05-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Templator', '0005_auto_20180518_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='D:\\WebGenerator\\Generator/uploads/media/2018.05.18 14.43.52', verbose_name='Attachment'),
        ),
    ]
